export enum RTag {
    DeclClass,
    DeclFunction,
    DeclTrait,
    DeclVariable,
    ExprCallField,
    ExprCallStatic,
    ExprConstant,
    ExprConstruct,
    ExprGetField,
    ExprGetLocal,
    ExprSetField,
    Generic,
    GenericApply,
    GenericParameter,
    ExprSetLocal,
    StmtReturn,
}
